{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Pipelines",
    "description" : "Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "To streamline customer support processes, use this API to retrieve your existing ticket pipelines and add new stages based on your business needs. Support reps can then assign tickets to those pipeline stages to track progress on customer issues.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Pipelines Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/pipelines"
    } ],
    "x-hubspot-introduction" : "Use the pipelines API to create and manage deal and ticket pipelines. Pipelines enable you to track the status or progress of deals and tickets, such as closing deals and opening support tickets."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  } ],
  "paths" : {
    "/crm/v3/pipelines/{objectType}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve all pipelines",
        "description" : "Return all pipelines for the object type specified by `{objectType}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePipelineNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a pipeline",
        "description" : "Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.",
        "operationId" : "post-/crm/v3/pipelines/{objectType}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelineInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Pipeline"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return a pipeline by ID",
        "description" : "Return a single pipeline object identified by its unique `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Pipeline"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Replace a pipeline",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "validateDealStageUsagesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "validateReferencesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelineReplaceInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Pipeline"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a pipeline",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "validateDealStageUsagesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "validateReferencesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "description" : "Perform a partial update of the pipeline identified by `{pipelineId}`. The updated pipeline will be returned in the response.",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "validateDealStageUsagesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "validateReferencesBeforeDelete",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelinePatchInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Pipeline"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/audit" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return an audit of all changes to the pipeline",
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicAuditInfoNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return all stages of a pipeline",
        "description" : "Return all the stages associated with the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePipelineStageNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a pipeline stage",
        "operationId" : "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelineStageInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PipelineStage"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Return a pipeline stage by ID",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "stageId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PipelineStage"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      },
      "put" : {
        "tags" : [ "Basic" ],
        "summary" : "Replace a pipeline stage",
        "description" : "Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "stageId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelineStageReplaceInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PipelineStage"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete a pipeline stage",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "stageId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "stageId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PipelineStagePatchInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PipelineStage"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit" : {
      "get" : {
        "tags" : [ "Basic" ],
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline stage identified by `{stageId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pipelineId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "pattern" : ".+",
            "type" : "string"
          }
        }, {
          "name" : "stageId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicAuditInfoNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ANY"
      }
    }
  },
  "components" : {
    "schemas" : {
      "PipelineStagePatchInput" : {
        "required" : [ "metadata" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Whether the pipeline is archived."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline."
          },
          "metadata" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A JSON object containing properties that are not present on all object pipelines.\n\nFor `deals` pipelines, the `probability` field is required (`{ \"probability\": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.\n\nFor `tickets` pipelines, the `ticketState` field is optional (`{ \"ticketState\": \"OPEN\" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`."
          }
        },
        "description" : "An input used to update some properties on a pipeline definition.",
        "example" : {
          "displayOrder" : 1,
          "label" : "Done",
          "metadata" : {
            "ticketState" : "CLOSED"
          }
        }
      },
      "PipelinePatchInput" : {
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Whether the pipeline is archived. This property should only be provided when restoring an archived pipeline. If it's provided in any other call, the request will fail and a `400 Bad Request` will be returned."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline. If two pipelines have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A unique label used to organize pipelines in HubSpot's UI"
          }
        },
        "description" : "An input used to update some properties on a pipeline definition.",
        "example" : {
          "displayOrder" : 0,
          "label" : "My updated pipeline"
        }
      },
      "PipelineStage" : {
        "required" : [ "archived", "createdAt", "displayOrder", "id", "label", "metadata", "updatedAt" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Whether the pipeline is archived."
          },
          "archivedAt" : {
            "type" : "string",
            "description" : "The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.",
            "format" : "date-time"
          },
          "createdAt" : {
            "type" : "string",
            "description" : "The date the pipeline stage was created. The stages on default pipelines will have createdAt = 0.",
            "format" : "date-time"
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "id" : {
            "type" : "string",
            "description" : "A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline stage."
          },
          "label" : {
            "type" : "string",
            "description" : "A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline."
          },
          "metadata" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A JSON object containing properties that are not present on all object pipelines.\n\nFor `deals` pipelines, the `probability` field is required (`{ \"probability\": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.\n\nFor `tickets` pipelines, the `ticketState` field is optional (`{ \"ticketState\": \"OPEN\" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`."
          },
          "updatedAt" : {
            "type" : "string",
            "description" : "The date the pipeline stage was last updated.",
            "format" : "date-time"
          },
          "writePermissions" : {
            "type" : "string",
            "description" : "Defines the level of write access for the pipeline stage, with possible values being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.",
            "enum" : [ "CRM_PERMISSIONS_ENFORCEMENT", "INTERNAL_ONLY", "READ_ONLY" ]
          }
        },
        "description" : "A pipeline stage definition.",
        "example" : {
          "archived" : false,
          "createdAt" : "2019-10-30T03:30:17.883Z",
          "displayOrder" : 0,
          "id" : "1234912",
          "label" : "In Progress",
          "metadata" : {
            "ticketState" : "OPEN"
          },
          "updatedAt" : "2019-12-07T16:50:06.678Z"
        }
      },
      "CollectionResponsePipelineStageNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PipelineStage"
            }
          }
        }
      },
      "PublicAuditInfo" : {
        "required" : [ "action", "identifier", "portalId" ],
        "type" : "object",
        "properties" : {
          "action" : {
            "type" : "string",
            "description" : "The action performed that triggered the audit event."
          },
          "fromUserId" : {
            "type" : "integer",
            "description" : "The ID of the user who initiated the audit event.",
            "format" : "int32"
          },
          "identifier" : {
            "type" : "string",
            "description" : "A unique string identifier for the audit event."
          },
          "message" : {
            "type" : "string",
            "description" : "A descriptive message related to the audit event."
          },
          "portalId" : {
            "type" : "integer",
            "description" : "The unique identifier for the HubSpot portal where the audit event occurred.",
            "format" : "int32"
          },
          "rawObject" : {
            "type" : "object",
            "properties" : { },
            "description" : "An object containing the raw data associated with the audit event."
          },
          "timestamp" : {
            "type" : "string",
            "description" : "The date and time when the audit event took place.",
            "format" : "date-time"
          }
        }
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "category" : {
            "type" : "string",
            "description" : "The error category"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{invalidPropertyName=[propertyValue], missingScopes=[scope1, scope2]}"
          },
          "correlationId" : {
            "type" : "string",
            "description" : "A unique identifier for the request. Include this value with any error reports or support tickets",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "errors" : {
            "type" : "array",
            "description" : "further information about the error",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A map of link names to associated URIs containing documentation about the error or recommended remediation steps"
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : "An error occurred"
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "CollectionResponsePublicAuditInfoNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicAuditInfo"
            }
          }
        }
      },
      "Pipeline" : {
        "required" : [ "archived", "createdAt", "displayOrder", "id", "label", "stages", "updatedAt" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Whether the pipeline is archived."
          },
          "archivedAt" : {
            "type" : "string",
            "description" : "The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.",
            "format" : "date-time"
          },
          "createdAt" : {
            "type" : "string",
            "description" : "The date the pipeline was created. The default pipelines will have createdAt = 0.",
            "format" : "date-time"
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline. If two pipelines have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "id" : {
            "type" : "string",
            "description" : "A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline."
          },
          "label" : {
            "type" : "string",
            "description" : "A unique label used to organize pipelines in HubSpot's UI"
          },
          "stages" : {
            "type" : "array",
            "description" : "The stages associated with the pipeline. They can be retrieved and updated via the pipeline stages endpoints.",
            "items" : {
              "$ref" : "#/components/schemas/PipelineStage"
            }
          },
          "updatedAt" : {
            "type" : "string",
            "description" : "The date the pipeline was last updated.",
            "format" : "date-time"
          }
        },
        "description" : "A pipeline definition.",
        "example" : {
          "archived" : false,
          "createdAt" : "2019-10-30T03:30:17.883Z",
          "displayOrder" : 0,
          "id" : "812723471",
          "label" : "My ticket pipeline",
          "stages" : [ {
            "archived" : false,
            "createdAt" : "2019-10-30T03:30:17.883Z",
            "displayOrder" : 0,
            "id" : "1234912",
            "label" : "In Progress",
            "metadata" : {
              "ticketState" : "OPEN"
            },
            "updatedAt" : "2019-12-07T16:50:06.678Z"
          }, {
            "archived" : false,
            "createdAt" : "2019-10-30T03:30:17.883Z",
            "displayOrder" : 0,
            "id" : "1234914",
            "label" : "Done",
            "metadata" : {
              "ticketState" : "CLOSED"
            },
            "updatedAt" : "2019-12-07T16:50:06.678Z"
          } ],
          "updatedAt" : "2019-12-07T16:50:06.678Z"
        }
      },
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "The status code associated with the error detail"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{missingScopes=[scope1, scope2]}"
          },
          "in" : {
            "type" : "string",
            "description" : "The name of the field or parameter in which the error was found."
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate"
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          }
        }
      },
      "PipelineStageInput" : {
        "required" : [ "displayOrder", "label", "metadata" ],
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline."
          },
          "metadata" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A JSON object containing properties that are not present on all object pipelines.\n\nFor `deals` pipelines, the `probability` field is required (`{ \"probability\": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.\n\nFor `tickets` pipelines, the `ticketState` field is optional (`{ \"ticketState\": \"OPEN\" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`."
          },
          "stageId" : {
            "type" : "string"
          }
        },
        "description" : "An input used to create or replace a pipeline stage's definition.",
        "example" : {
          "displayOrder" : 1,
          "label" : "Done",
          "metadata" : {
            "ticketState" : "CLOSED"
          }
        }
      },
      "CollectionResponsePipelineNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Pipeline"
            }
          }
        }
      },
      "PipelineInput" : {
        "required" : [ "displayOrder", "label", "stages" ],
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline. If two pipelines have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A unique label used to organize pipelines in HubSpot's UI"
          },
          "pipelineId" : {
            "type" : "string"
          },
          "stages" : {
            "type" : "array",
            "description" : "Pipeline stage inputs used to create the new or replacement pipeline.",
            "items" : {
              "$ref" : "#/components/schemas/PipelineStageInput"
            }
          }
        },
        "description" : "An input used to create or replace a pipeline's definition.",
        "example" : {
          "displayOrder" : 0,
          "label" : "My replaced pipeline",
          "stages" : [ {
            "displayOrder" : 0,
            "label" : "In Progress",
            "metadata" : {
              "ticketState" : "OPEN"
            }
          }, {
            "displayOrder" : 1,
            "label" : "Done",
            "metadata" : {
              "ticketState" : "CLOSED"
            }
          } ]
        }
      },
      "PipelineReplaceInput" : {
        "required" : [ "displayOrder", "label", "stages" ],
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline."
          },
          "stages" : {
            "type" : "array",
            "description" : "The stages associated with the pipeline. They can be retrieved and updated via the pipeline stages endpoints.",
            "items" : {
              "$ref" : "#/components/schemas/PipelineStageInput"
            }
          }
        }
      },
      "PipelineStageReplaceInput" : {
        "required" : [ "displayOrder", "label", "metadata" ],
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline."
          },
          "metadata" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A JSON object containing properties that are not present on all object pipelines.\n\nFor `deals` pipelines, the `probability` field is required (`{ \"probability\": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.\n\nFor `tickets` pipelines, the `ticketState` field is optional (`{ \"ticketState\": \"OPEN\" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`."
          }
        }
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "properties-settings-read" : "",
              "properties-settings-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}