{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Properties",
    "description" : "All HubSpot objects store data in default and custom properties. These endpoints provide access to read and modify object properties in HubSpot.",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Create a set of custom multi-select properties for storing contract data on company records.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Properties guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/crm/properties"
    } ],
    "x-hubspot-introduction" : "Use the properties API to store information in fields on individual contact records. You can use this API to manage existing default and custom properties, create new custom properties, and more."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Core"
  } ],
  "paths" : {
    "/crm/v3/properties/{objectType}" : {
      "get" : {
        "tags" : [ "Core" ],
        "summary" : "Read all properties",
        "description" : "Read all existing properties for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/v3/properties/{objectType}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "archived",
          "in" : "query",
          "description" : "Whether to return only results that have been archived.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "dataSensitivity",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "highly_sensitive", "non_sensitive", "sensitive" ],
            "default" : "non_sensitive"
          }
        }, {
          "name" : "locale",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "properties",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePropertyNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Core" ],
        "summary" : "Create a property",
        "description" : "Create and return a copy of a new property for the specified object type.",
        "operationId" : "post-/crm/v3/properties/{objectType}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PropertyCreate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Property"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of properties",
        "description" : "Archive a provided list of properties. This method will return a 204 No Content response on success regardless of the initial state of the property (e.g. active, already archived, non-existent).",
        "operationId" : "post-/crm/v3/properties/{objectType}/batch/archive",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchInputPropertyName"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of properties",
        "description" : "Create a batch of properties using the same rules as when creating an individual property.",
        "operationId" : "post-/crm/v3/properties/{objectType}/batch/create",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchInputPropertyCreate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseProperty"
                }
              }
            }
          },
          "207" : {
            "description" : "multiple statuses",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponsePropertyWithErrors"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of properties",
        "description" : "Read a provided list of properties.",
        "operationId" : "post-/crm/v3/properties/{objectType}/batch/read",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "locale",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchReadInputPropertyName"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseProperty"
                }
              }
            }
          },
          "207" : {
            "description" : "multiple statuses",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponsePropertyWithErrors"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/groups" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read all property groups",
        "description" : "Read all existing property groups for the specified object type and HubSpot account.",
        "operationId" : "get-/crm/v3/properties/{objectType}/groups",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "locale",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePropertyGroupNoPaging"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create a property group",
        "description" : "Create and return a copy of a new property group.",
        "operationId" : "post-/crm/v3/properties/{objectType}/groups",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PropertyGroupCreate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PropertyGroup"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/groups/{groupName}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read a property group",
        "description" : "Read a property group identified by {groupName}.",
        "operationId" : "get-/crm/v3/properties/{objectType}/groups/{groupName}",
        "parameters" : [ {
          "name" : "groupName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "locale",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PropertyGroup"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive a property group",
        "description" : "Move a property group identified by {groupName} to the recycling bin.",
        "operationId" : "delete-/crm/v3/properties/{objectType}/groups/{groupName}",
        "parameters" : [ {
          "name" : "groupName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update a property group",
        "description" : "Perform a partial update of a property group identified by {groupName}. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/v3/properties/{objectType}/groups/{groupName}",
        "parameters" : [ {
          "name" : "groupName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PropertyGroupUpdate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PropertyGroup"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    },
    "/crm/v3/properties/{objectType}/{propertyName}" : {
      "get" : {
        "tags" : [ "Core" ],
        "summary" : "Read a property",
        "description" : "Read a property identified by {propertyName}.",
        "operationId" : "get-/crm/v3/properties/{objectType}/{propertyName}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "propertyName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "archived",
          "in" : "query",
          "description" : "Whether to return only results that have been archived.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "dataSensitivity",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "highly_sensitive", "non_sensitive", "sensitive" ],
            "default" : "non_sensitive"
          }
        }, {
          "name" : "locale",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "properties",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Property"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-read" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-read" ]
        }, {
          "oauth2" : [ "properties-settings-read" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "delete" : {
        "tags" : [ "Core" ],
        "summary" : "Archive a property",
        "description" : "Move a property identified by {propertyName} to the recycling bin.",
        "operationId" : "delete-/crm/v3/properties/{objectType}/{propertyName}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "propertyName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      },
      "patch" : {
        "tags" : [ "Core" ],
        "summary" : "Update a property",
        "description" : "Perform a partial update of a property identified by { propertyName }. Provided fields will be overwritten.",
        "operationId" : "patch-/crm/v3/properties/{objectType}/{propertyName}",
        "parameters" : [ {
          "name" : "objectType",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "propertyName",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PropertyUpdate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Property"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "app_cookie" : [ "properties-settings-write" ]
        }, {
          "hapikey" : [ ]
        }, {
          "internal_cookie" : [ "properties-settings-write" ]
        }, {
          "oauth2" : [ "properties-settings-write" ]
        }, {
          "shhkey" : [ ]
        } ],
        "x-hubspot-auth-scoping-type" : "ALL"
      }
    }
  },
  "components" : {
    "schemas" : {
      "PropertyName" : {
        "required" : [ "name" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "The name of the property to read or modify."
          }
        },
        "example" : {
          "name" : "my_custom_property"
        }
      },
      "StandardError" : {
        "required" : [ "category", "context", "errors", "links", "message", "status" ],
        "type" : "object",
        "properties" : {
          "category" : {
            "type" : "string",
            "description" : "The main category of the error."
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Additional context-specific information related to the error."
          },
          "errors" : {
            "type" : "array",
            "description" : "The detailed error objects.",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          },
          "id" : {
            "type" : "string",
            "description" : "A unique ID for the error instance."
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "URLs linking to documentation or resources associated with the error."
          },
          "message" : {
            "type" : "string",
            "description" : "A human-readable string describing the error and possible remediation steps."
          },
          "status" : {
            "type" : "string",
            "description" : "The HTTP status code associated with the error."
          },
          "subCategory" : {
            "type" : "object",
            "properties" : { },
            "description" : "A more specific error category within each main category."
          }
        },
        "description" : "Represents a standard error response in the HubSpot API, providing detailed information about an error that occurred during an API request."
      },
      "BatchResponseProperty" : {
        "required" : [ "completedAt", "results", "startedAt", "status" ],
        "type" : "object",
        "properties" : {
          "completedAt" : {
            "type" : "string",
            "description" : "The timestamp indicating when the batch operation was completed.",
            "format" : "date-time"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A collection of URLs linking to documentation or resources related to the batch operation."
          },
          "requestedAt" : {
            "type" : "string",
            "description" : "The timestamp indicating when the batch operation was requested.",
            "format" : "date-time"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Property"
            }
          },
          "startedAt" : {
            "type" : "string",
            "description" : "The timestamp indicating when the batch operation began processing.",
            "format" : "date-time"
          },
          "status" : {
            "type" : "string",
            "description" : "The current status of the batch operation, with possible values being CANCELED, COMPLETE, PENDING, or PROCESSING.",
            "enum" : [ "CANCELED", "COMPLETE", "PENDING", "PROCESSING" ]
          }
        }
      },
      "PropertyGroup" : {
        "required" : [ "archived", "displayOrder", "label", "name" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Indicates whether the property group is archived."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Property groups are displayed in order starting with the lowest positive integer value. Values of -1 will cause the property group to be displayed after any positive values.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable label that will be shown in HubSpot."
          },
          "name" : {
            "type" : "string",
            "description" : "The internal property group name, which must be used when referencing the property group via the API."
          }
        },
        "description" : "An ID for a group of properties",
        "example" : {
          "displayOrder" : -1,
          "label" : "My Property Group",
          "name" : "mypropertygroup"
        }
      },
      "CollectionResponsePropertyGroupNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PropertyGroup"
            }
          }
        }
      },
      "PropertyCreate" : {
        "required" : [ "fieldType", "groupName", "label", "name", "type" ],
        "type" : "object",
        "properties" : {
          "calculationFormula" : {
            "type" : "string",
            "description" : "Represents a formula that is used to compute a calculated property."
          },
          "currencyPropertyName" : {
            "type" : "string"
          },
          "dataSensitivity" : {
            "type" : "string",
            "description" : "Indicates the sensitivity level of the property, with options: highly_sensitive, non_sensitive, or sensitive.",
            "enum" : [ "highly_sensitive", "non_sensitive", "sensitive" ]
          },
          "description" : {
            "type" : "string",
            "description" : "A description of the property that will be shown as help text in HubSpot."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Properties are displayed in order starting with the lowest positive integer value. Values of -1 will cause the property to be displayed after any positive values.",
            "format" : "int32"
          },
          "externalOptions" : {
            "type" : "boolean",
            "description" : "Applicable only for 'enumeration' type properties.  Should be set to true in conjunction with a 'referencedObjectType' of 'OWNER'.  Otherwise false."
          },
          "fieldType" : {
            "type" : "string",
            "description" : "Controls how the property appears in HubSpot.",
            "enum" : [ "booleancheckbox", "calculation_equation", "checkbox", "date", "file", "html", "number", "phonenumber", "radio", "select", "text", "textarea" ]
          },
          "formField" : {
            "type" : "boolean",
            "description" : "Whether or not the property can be used in a HubSpot form."
          },
          "groupName" : {
            "type" : "string",
            "description" : "The name of the property group the property belongs to."
          },
          "hasUniqueValue" : {
            "type" : "boolean",
            "description" : "Whether or not the property's value must be unique. Once set, this can't be changed."
          },
          "hidden" : {
            "type" : "boolean",
            "description" : "If true, the property won't be visible and can't be used in HubSpot."
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable property label that will be shown in HubSpot."
          },
          "name" : {
            "type" : "string",
            "description" : "The internal property name, which must be used when referencing the property via the API."
          },
          "numberDisplayHint" : {
            "type" : "string",
            "enum" : [ "currency", "duration", "formatted", "percentage", "probability", "unformatted" ]
          },
          "options" : {
            "type" : "array",
            "description" : "A list of valid options for the property. This field is required for enumerated properties.",
            "items" : {
              "$ref" : "#/components/schemas/OptionInput"
            }
          },
          "referencedObjectType" : {
            "type" : "string",
            "description" : "Should be set to 'OWNER' when 'externalOptions' is true, which causes the property to dynamically pull option values from the current HubSpot users."
          },
          "showCurrencySymbol" : {
            "type" : "boolean"
          },
          "type" : {
            "type" : "string",
            "description" : "The data type of the property.",
            "enum" : [ "bool", "date", "datetime", "enumeration", "number", "phone_number", "string" ]
          }
        },
        "example" : {
          "displayOrder" : 2,
          "fieldType" : "select",
          "formField" : true,
          "groupName" : "contactinformation",
          "hasUniqueValue" : false,
          "hidden" : false,
          "label" : "My Contact Property",
          "name" : "my_contact_property",
          "options" : [ {
            "description" : "Choice number one",
            "displayOrder" : 1,
            "hidden" : false,
            "label" : "Option A",
            "value" : "A"
          }, {
            "description" : "Choice number two",
            "displayOrder" : 2,
            "hidden" : false,
            "label" : "Option B",
            "value" : "B"
          } ],
          "type" : "enumeration"
        }
      },
      "OptionInput" : {
        "required" : [ "hidden", "label", "value" ],
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string",
            "description" : "A description of the option."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Options are shown in order starting with the lowest positive integer value. Values of -1 will cause the option to be displayed after any positive values.",
            "format" : "int32"
          },
          "hidden" : {
            "type" : "boolean",
            "description" : "Hidden options won't be shown in HubSpot."
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable option label that will be shown in HubSpot."
          },
          "value" : {
            "type" : "string",
            "description" : "The internal value of the option, which must be used when setting the property value through the API."
          }
        },
        "example" : {
          "description" : "Choice number one",
          "displayOrder" : 1,
          "hidden" : false,
          "label" : "Option A",
          "value" : "A"
        }
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "category" : {
            "type" : "string",
            "description" : "The error category"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{invalidPropertyName=[propertyValue], missingScopes=[scope1, scope2]}"
          },
          "correlationId" : {
            "type" : "string",
            "description" : "A unique identifier for the request. Include this value with any error reports or support tickets",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "errors" : {
            "type" : "array",
            "description" : "further information about the error",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A map of link names to associated URIs containing documentation about the error or recommended remediation steps"
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : "An error occurred"
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "BatchInputPropertyCreate" : {
        "required" : [ "inputs" ],
        "type" : "object",
        "properties" : {
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PropertyCreate"
            }
          }
        }
      },
      "CollectionResponsePropertyNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Property"
            }
          }
        }
      },
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "The status code associated with the error detail"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{missingScopes=[scope1, scope2]}"
          },
          "in" : {
            "type" : "string",
            "description" : "The name of the field or parameter in which the error was found."
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate"
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          }
        }
      },
      "PropertyUpdate" : {
        "type" : "object",
        "properties" : {
          "calculationFormula" : {
            "type" : "string",
            "description" : "Represents a formula that is used to compute a calculated property."
          },
          "currencyPropertyName" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string",
            "description" : "A description of the property that will be shown as help text in HubSpot."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Properties are displayed in order starting with the lowest positive integer value. Values of -1 will cause the Property to be displayed after any positive values.",
            "format" : "int32"
          },
          "fieldType" : {
            "type" : "string",
            "description" : "Controls how the property appears in HubSpot.",
            "enum" : [ "booleancheckbox", "calculation_equation", "checkbox", "date", "file", "html", "number", "phonenumber", "radio", "select", "text", "textarea" ]
          },
          "formField" : {
            "type" : "boolean",
            "description" : "Whether or not the property can be used in a HubSpot form."
          },
          "groupName" : {
            "type" : "string",
            "description" : "The name of the property group the property belongs to."
          },
          "hidden" : {
            "type" : "boolean",
            "description" : "If true, the property won't be visible and can't be used in HubSpot."
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable property label that will be shown in HubSpot."
          },
          "numberDisplayHint" : {
            "type" : "string",
            "enum" : [ "currency", "duration", "formatted", "percentage", "probability", "unformatted" ]
          },
          "options" : {
            "type" : "array",
            "description" : "A list of valid options for the property.",
            "items" : {
              "$ref" : "#/components/schemas/OptionInput"
            }
          },
          "showCurrencySymbol" : {
            "type" : "boolean"
          },
          "type" : {
            "type" : "string",
            "description" : "The data type of the property.",
            "enum" : [ "bool", "date", "datetime", "enumeration", "number", "phone_number", "string" ]
          }
        },
        "example" : {
          "displayOrder" : 2,
          "fieldType" : "select",
          "formField" : true,
          "groupName" : "contactinformation",
          "hidden" : false,
          "label" : "My Contact Property",
          "name" : "my_contact_property",
          "options" : [ {
            "description" : "Choice number one",
            "displayOrder" : 1,
            "hidden" : false,
            "label" : "Option A",
            "value" : "A"
          }, {
            "description" : "Choice number two",
            "displayOrder" : 2,
            "hidden" : false,
            "label" : "Option B",
            "value" : "B"
          } ],
          "type" : "enumeration"
        }
      },
      "BatchReadInputPropertyName" : {
        "required" : [ "archived", "dataSensitivity", "inputs" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Specifies whether the property is archived."
          },
          "dataSensitivity" : {
            "type" : "string",
            "description" : "Indicates the sensitivity level of the data, such as 'non_sensitive', 'sensitive', or 'highly_sensitive'.",
            "enum" : [ "highly_sensitive", "non_sensitive", "sensitive" ]
          },
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PropertyName"
            }
          }
        }
      },
      "PropertyGroupCreate" : {
        "required" : [ "label", "name" ],
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "Property groups are displayed in order starting with the lowest positive integer value. Values of -1 will cause the property group to be displayed after any positive values.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable label that will be shown in HubSpot."
          },
          "name" : {
            "type" : "string",
            "description" : "The internal property group name, which must be used when referencing the property group via the API."
          }
        },
        "example" : {
          "displayOrder" : -1,
          "label" : "My Property Group",
          "name" : "mypropertygroup"
        }
      },
      "PropertyModificationMetadata" : {
        "required" : [ "archivable", "readOnlyDefinition", "readOnlyValue" ],
        "type" : "object",
        "properties" : {
          "archivable" : {
            "type" : "boolean",
            "description" : "Specifies whether the property can be archived."
          },
          "readOnlyDefinition" : {
            "type" : "boolean",
            "description" : "Indicates whether the property's definition is read-only and cannot be modified."
          },
          "readOnlyOptions" : {
            "type" : "boolean",
            "description" : "Indicates whether the property's options are read-only and cannot be modified."
          },
          "readOnlyValue" : {
            "type" : "boolean",
            "description" : "Indicates whether the property's value is read-only and cannot be modified."
          }
        }
      },
      "BatchInputPropertyName" : {
        "required" : [ "inputs" ],
        "type" : "object",
        "properties" : {
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PropertyName"
            }
          }
        }
      },
      "BatchResponsePropertyWithErrors" : {
        "required" : [ "completedAt", "results", "startedAt", "status" ],
        "type" : "object",
        "properties" : {
          "completedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/StandardError"
            }
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "numErrors" : {
            "type" : "integer",
            "format" : "int32"
          },
          "requestedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Property"
            }
          },
          "startedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "status" : {
            "type" : "string",
            "enum" : [ "CANCELED", "COMPLETE", "PENDING", "PROCESSING" ]
          }
        }
      },
      "Option" : {
        "required" : [ "hidden", "label", "value" ],
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string",
            "description" : "A description of the option."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Options are displayed in order starting with the lowest positive integer value. Values of -1 will cause the option to be displayed after any positive values.",
            "format" : "int32"
          },
          "hidden" : {
            "type" : "boolean",
            "description" : "Hidden options will not be displayed in HubSpot."
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable option label that will be shown in HubSpot."
          },
          "value" : {
            "type" : "string",
            "description" : "The internal value of the option, which must be used when setting the property value through the API."
          }
        },
        "description" : "A HubSpot property option",
        "example" : {
          "description" : "Choice number one",
          "displayOrder" : 1,
          "hidden" : false,
          "label" : "Option A",
          "value" : "A"
        }
      },
      "PropertyGroupUpdate" : {
        "type" : "object",
        "properties" : {
          "displayOrder" : {
            "type" : "integer",
            "description" : "Property groups are displayed in order starting with the lowest positive integer value. Values of -1 will cause the property group to be displayed after any positive values.",
            "format" : "int32"
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable label that will be shown in HubSpot."
          }
        },
        "example" : {
          "displayOrder" : -1,
          "label" : "My Property Group"
        }
      },
      "Property" : {
        "required" : [ "description", "fieldType", "groupName", "label", "name", "options", "type" ],
        "type" : "object",
        "properties" : {
          "archived" : {
            "type" : "boolean",
            "description" : "Whether or not the property is archived."
          },
          "archivedAt" : {
            "type" : "string",
            "description" : "When the property was archived.",
            "format" : "date-time"
          },
          "calculated" : {
            "type" : "boolean",
            "description" : "For default properties, true indicates that the property is calculated by a HubSpot process. It has no effect for custom properties."
          },
          "calculationFormula" : {
            "type" : "string",
            "description" : "Represents a formula that is used to compute a calculated property."
          },
          "createdAt" : {
            "type" : "string",
            "description" : "The timestamp when the property was created, in ISO 8601 format.",
            "format" : "date-time"
          },
          "createdUserId" : {
            "type" : "string",
            "description" : "The internal user ID of the user who created the property in HubSpot. This field may not exist if the property was created outside of HubSpot."
          },
          "currencyPropertyName" : {
            "type" : "string",
            "description" : "The name of the related currency property."
          },
          "dataSensitivity" : {
            "type" : "string",
            "description" : "Indicates the sensitivity level of the property, such as \"non_sensitive\", \"sensitive\", or \"highly_sensitive\".",
            "enum" : [ "highly_sensitive", "non_sensitive", "sensitive" ]
          },
          "dateDisplayHint" : {
            "type" : "string",
            "description" : "Indicates how date values should be displayed, with options such as 'absolute', 'absolute_with_relative', 'time_since', or 'time_until'.",
            "enum" : [ "absolute", "absolute_with_relative", "time_since", "time_until" ]
          },
          "description" : {
            "type" : "string",
            "description" : "A description of the property that will be shown as help text in HubSpot."
          },
          "displayOrder" : {
            "type" : "integer",
            "description" : "Properties are shown in order, starting with the lowest positive integer value.",
            "format" : "int32"
          },
          "externalOptions" : {
            "type" : "boolean",
            "description" : "For default properties, true indicates that the options are stored externally to the property settings."
          },
          "fieldType" : {
            "type" : "string",
            "description" : "Controls how the property appears in HubSpot."
          },
          "formField" : {
            "type" : "boolean",
            "description" : "Whether or not the property can be used in a HubSpot form."
          },
          "groupName" : {
            "type" : "string",
            "description" : "The name of the property group the property belongs to."
          },
          "hasUniqueValue" : {
            "type" : "boolean",
            "description" : "Whether or not the property's value must be unique. Once set, this can't be changed."
          },
          "hidden" : {
            "type" : "boolean",
            "description" : "Whether or not the property will be hidden from the HubSpot UI. It's recommended this be set to false for custom properties.",
            "example" : false
          },
          "hubspotDefined" : {
            "type" : "boolean",
            "description" : "This will be true for default object properties built into HubSpot."
          },
          "label" : {
            "type" : "string",
            "description" : "A human-readable property label that will be shown in HubSpot."
          },
          "modificationMetadata" : {
            "$ref" : "#/components/schemas/PropertyModificationMetadata"
          },
          "name" : {
            "type" : "string",
            "description" : "The internal property name, which must be used when referencing the property via the API."
          },
          "numberDisplayHint" : {
            "type" : "string",
            "description" : "Hint for how a number property is displayed and validated in HubSpot's UI. Can be: \"unformatted\", \"formatted\", \"currency\", \"percentage\", \"duration\", or \"probability\".",
            "enum" : [ "currency", "duration", "formatted", "percentage", "probability", "unformatted" ]
          },
          "options" : {
            "type" : "array",
            "description" : "A list of valid options for the property. This field is required for enumerated properties, but will be empty for other property types.",
            "items" : {
              "$ref" : "#/components/schemas/Option"
            }
          },
          "referencedObjectType" : {
            "type" : "string",
            "description" : "If this property is related to other object(s), they'll be listed here."
          },
          "sensitiveDataCategories" : {
            "type" : "array",
            "description" : "When sensitiveData is true, lists the type of sensitive data contained in the property (e.g., \"HIPAA\").",
            "items" : {
              "type" : "string"
            }
          },
          "showCurrencySymbol" : {
            "type" : "boolean",
            "description" : "Whether or not the property will display the currency symbol set in the account settings."
          },
          "type" : {
            "type" : "string",
            "description" : "The property data type."
          },
          "updatedAt" : {
            "type" : "string",
            "description" : "The timestamp when the property was last updated, in ISO 8601 format.",
            "format" : "date-time"
          },
          "updatedUserId" : {
            "type" : "string",
            "description" : "The internal user ID of the user who updated the property in HubSpot. This field may not exist if the property was updated outside of HubSpot."
          }
        },
        "description" : "A HubSpot property",
        "example" : {
          "displayOrder" : 2,
          "fieldType" : "select",
          "formField" : true,
          "groupName" : "contactinformation",
          "hasUniqueValue" : false,
          "hidden" : false,
          "label" : "My Contact Property",
          "modificationMetadata" : {
            "archivable" : true,
            "readOnlyDefinition" : false,
            "readOnlyOptions" : false,
            "readOnlyValue" : false
          },
          "name" : "my_contact_property",
          "options" : [ {
            "description" : "Choice number one",
            "displayOrder" : 1,
            "hidden" : false,
            "label" : "Option A",
            "value" : "A"
          }, {
            "description" : "Choice number two",
            "displayOrder" : 2,
            "hidden" : false,
            "label" : "Option B",
            "value" : "B"
          } ],
          "type" : "enumeration"
        }
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "properties-settings-read" : "",
              "properties-settings-write" : ""
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}